### ISSUE TITLE
[BUG] Can't download full Half-Life 2, complain about manifest didn't return request for some depot. 

### ISSUE THREAD

**Issue by TheKingFireS** [SteamRE/DepotDownloader#569]
### What did you expect to happen?

Actually downloading full Half-Life 2, including EP1, EP2 and LC.

### Instead of that, what actually happened?

Stopped at 380, or 420 and 340 if you use `-depot` flag due to manifest didn't return request.

### Which operating system are you running on?

Linux

### Version

2.7.4

### Command

./DepotDownloader -username user -app 220 -dir test -validate

### Relevant log output

```shell
Using Steam3 suggested CellID: 14
Got 147 licenses for account!
Got AppInfo for 220
Using app branch: 'public'.
Got depot key for 233 result: OK
Got depot key for 234 result: OK
Got depot key for 221 result: OK
Got depot key for 224 result: OK
Got AppInfo for 380
Got depot key for 389 result: OK
Got depot key for 380 result: OK
Got AppInfo for 420
Got depot key for 420 result: OK
Got AppInfo for 340
Got depot key for 340 result: OK
Processing depot 233
Downloading depot manifest... Got manifest request code for 233 6456625705059535223 result: 14089553916440794106
 Done!
Manifest 6456625705059535223 (11/16/2024 17:07:59)
Processing depot 234
Downloading depot manifest... Got manifest request code for 234 488462887721122399 result: 2868494448938403688
 Done!
Manifest 488462887721122399 (09/12/2013 17:57:57)
Processing depot 221
Downloading depot manifest... Got manifest request code for 221 5471242560939121622 result: 4493048593414813128
 Done!
Manifest 5471242560939121622 (11/16/2024 17:07:26)
Processing depot 224
Downloading depot manifest... Got manifest request code for 224 2150834866873080441 result: 3310142608086251928
 Done!
Manifest 2150834866873080441 (11/16/2024 17:07:41)
Processing depot 389
Downloading depot manifest... Got manifest request code for 389 7499064160519937441 result: 2604606055778850676
 Done!
Manifest 7499064160519937441 (11/15/2024 20:04:45)
Processing depot 380
Downloading depot manifest... Got manifest request code for 380 1953180749841724978 result: 0
No manifest request code was returned for 380 1953180749841724978
Encountered 401 for depot manifest 380 1953180749841724978. Aborting.

Unable to download manifest 1953180749841724978 for depot 380
App 220 was not completely downloaded.
The operation was canceled.
Disconnected from Steam
```

### Additional Information

Used official binaries, ran from Debian 12 updated to latest.

Half-Life: 2 Lost Coast, EP1 and EP2 are unlisted and can't be bought from Steam since it got merged with main Half-Life 2, it could be one who caused.

**Comment by NicknineTheEagle** [comment]
Looks like the behavior reverted in https://github.com/SteamRE/DepotDownloader/commit/3143362d83b0f6753e48b50fa7e06735756b2361 is now correct.

**Comment by Dimensional** [comment]
I've not been getting errors when downloading the manifests. I'm thinking that the steam CDN servers are just having issues returning request codes from time to time, as I've been seeing this randomly myself and with others.

**Comment by NicknineTheEagle** [comment]
> I've not been getting errors when downloading the manifests. I'm thinking that the steam CDN servers are just having issues returning request codes from time to time, as I've been seeing this randomly myself and with others.

I tested 220 after seeing this issue I was 100% consistently getting request code error on depot 380. It was then fixed by PR change.

**Comment by mrpijey** [comment]
How was this solved? I still get the issue with this title, and I've seen several reports of similar issues, but no practical resolution to the issue.

**Comment by TheKingFireS** [comment]
> How was this solved? I still get the issue with this title, and I've seen several reports of similar issues, but no practical resolution to the issue.

Use the latest git (aka nightly). It's solved for me.
